//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMPLOYEE
    {
        public int EMPLOYEE_ID { get; set; }
        public Nullable<int> EMPLOYEE_NO { get; set; }
        public string FULLNAME_TH { get; set; }
        public string FULLNAME_EN { get; set; }
        public string NICKNAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string ZODIAC { get; set; }
        public string POSITION { get; set; }
        public string POSITION_LEVEL { get; set; }
        public string COMPANY { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string MAIL_PTT_DIGITAL { get; set; }
        public string MAIL_OTHER { get; set; }
        public string LINE_ID { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> INTERVIEW_DATE { get; set; }
        public Nullable<System.DateTime> START_WORK_DATE { get; set; }
        public string STATUS { get; set; }
    }
}
