//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROJECT
    {
        public int PROJECT_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string STATUS { get; set; }
        public string REMARK { get; set; }
        public string JOBCODE_NO { get; set; }
    }
}
